name: buildpr

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          scripts/install.sh
      - name: pxt ci
        run: |
          cd pxt-lets-steam;pxt ci
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true

